[workspace]
authors = ["Brian-M-J <brianmj02@gmail.com>"]
channels = ["conda-forge"]
name = "drl_ad_mini_project"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.3,<3.14"

[pypi-dependencies]
highway-env = ">=1.10.1, <2"
gymnasium = ">=1.1.1, <2"
stable-baselines3 = { version = ">=2.6.0, <3", extras = ["extra"] }
torch = ">=2.7.0, <3"
shap = ">=0.47.2, <0.48"
numpy = ">=2.2.5, <3"
pandas = ">=2.2.3, <3"
matplotlib = ">=3.10.1, <4"
seaborn = ">=0.13.2, <0.14"
